"""Issue the laptop's IAM Roles Anywhere certificate, with the private key inside the TPM.

    python scripts/roles_anywhere_cert.py issue      # Windows: new TPM key + CSR, sign, install
    python scripts/roles_anywhere_cert.py show       # the installed certificate (public data only)
    python scripts/roles_anywhere_cert.py trust ARN  # iam/operator/trust.local.json for the console

Why: the laptop's long-lived access key is replaced by IAM Roles Anywhere. The key that proves
the laptop's identity is created by Windows inside the TPM (Microsoft Platform Crypto Provider,
non-exportable), so it cannot be copied off the machine the way an access key file can.
`aws_signing_helper --cert-selector` finds the certificate in the user's "MY" store and asks the
TPM to sign; the helper never sees the key.

The certificate authority is created in memory for one signature and then discarded - its private
key is never written anywhere, so there is no CA key to steal. The trust anchor in AWS holds only
the CA certificate (public). Renewal = run `issue` again and replace the trust anchor's
certificate bundle (same anchor, same ARN, so no trust policy changes).

What IAM Roles Anywhere requires (docs, trust-model.html, read 2026-09-28):
  end entity: X.509v3, basicConstraints CA=false if present, keyUsage digitalSignature, SHA-256+
  anchor CA:  X.509v3, basicConstraints CA=true, keyUsage keyCertSign (cRLSign allowed), SHA-256+
Files written to ~/.warden/roles-anywhere/: request.inf, request.csr, ca.pem, laptop.pem. All are
public material. Nothing here is a secret.
"""

from __future__ import annotations

import argparse
import datetime as dt
import pathlib
import re
import subprocess  # nosec B404
import sys

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509.oid import ExtendedKeyUsageOID, NameOID

SUBJECT_CN = "warden-operator-laptop"
ORG = "warden"
DAYS = 365
OUT = pathlib.Path.home() / ".warden" / "roles-anywhere"

# certreq request: the key is generated by the TPM and marked non-exportable.
INF = f"""[Version]
Signature = "$Windows NT$"

[NewRequest]
Subject = "CN={SUBJECT_CN}, O={ORG}"
KeyAlgorithm = ECDSA_P256
KeyLength = 256
ProviderName = "Microsoft Platform Crypto Provider"
MachineKeySet = FALSE
Exportable = FALSE
KeyUsage = 0x80
KeyUsageProperty = 2
RequestType = PKCS10
HashAlgorithm = SHA256
FriendlyName = "WARDEN operator (IAM Roles Anywhere)"
"""


def issue(csr_pem: bytes, now: dt.datetime, days: int = DAYS) -> tuple[bytes, bytes]:
    """Sign the CSR with a fresh, in-memory CA. Returns (ca_pem, leaf_pem). The CA key dies here."""
    csr = x509.load_pem_x509_csr(csr_pem)
    if not csr.is_signature_valid:
        raise ValueError("CSR signature does not verify")
    cns = csr.subject.get_attributes_for_oid(NameOID.COMMON_NAME)
    if [a.value for a in cns] != [SUBJECT_CN]:
        raise ValueError(f"CSR subject CN must be exactly {SUBJECT_CN!r}")
    # The role's trust policy pins x509Subject/O too; a certificate without it could never assume.
    orgs = csr.subject.get_attributes_for_oid(NameOID.ORGANIZATION_NAME)
    if [a.value for a in orgs] != [ORG]:
        raise ValueError(f"CSR subject O must be exactly {ORG!r}")

    ca_key = ec.generate_private_key(ec.SECP256R1())
    ca_name = x509.Name([
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, ORG),
        x509.NameAttribute(NameOID.COMMON_NAME, f"warden-operator-ca-{now:%Y%m%d}"),
    ])
    start, end = now - dt.timedelta(minutes=5), now + dt.timedelta(days=days)
    ca_ski = x509.SubjectKeyIdentifier.from_public_key(ca_key.public_key())
    ca = (
        x509.CertificateBuilder()
        .subject_name(ca_name).issuer_name(ca_name)
        .public_key(ca_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(start).not_valid_after(end + dt.timedelta(days=1))
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .add_extension(x509.KeyUsage(
            digital_signature=False, content_commitment=False, key_encipherment=False,
            data_encipherment=False, key_agreement=False, key_cert_sign=True, crl_sign=True,
            encipher_only=False, decipher_only=False), critical=True)
        .add_extension(ca_ski, critical=False)
        .sign(ca_key, hashes.SHA256())
    )
    leaf = (
        x509.CertificateBuilder()
        .subject_name(csr.subject).issuer_name(ca_name)
        .public_key(csr.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(start).not_valid_after(end)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(x509.KeyUsage(
            digital_signature=True, content_commitment=False, key_encipherment=False,
            data_encipherment=False, key_agreement=False, key_cert_sign=False, crl_sign=False,
            encipher_only=False, decipher_only=False), critical=True)
        .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.CLIENT_AUTH]), critical=False)
        .add_extension(x509.SubjectKeyIdentifier.from_public_key(csr.public_key()), critical=False)
        .add_extension(x509.AuthorityKeyIdentifier.from_issuer_subject_key_identifier(ca_ski),
                       critical=False)
        .sign(ca_key, hashes.SHA256())
    )
    del ca_key  # ponytail: in-memory CA, discarded; renewal re-issues CA + updates the anchor
    enc = serialization.Encoding.PEM
    return ca.public_bytes(enc), leaf.public_bytes(enc)


ANCHOR_ARN = re.compile(r"arn:aws:rolesanywhere:ap-south-2:(\d{12}):trust-anchor/([0-9a-f-]{36})")
TRUST = pathlib.Path(__file__).resolve().parents[1] / "iam" / "operator" / "trust.json"


def render_trust(anchor_arn: str) -> str:
    """iam/operator/trust.json with the real anchor filled in - for the local, gitignored copy."""
    m = ANCHOR_ARN.fullmatch(anchor_arn.strip())
    if not m:
        raise ValueError("expected arn:aws:rolesanywhere:ap-south-2:<12 digits>:trust-anchor/<uuid>")
    return (TRUST.read_text(encoding="utf-8")
            .replace("<ACCOUNT_ID>", m.group(1)).replace("<TRUST_ANCHOR_ID>", m.group(2)))


def write_trust(anchor_arn: str) -> pathlib.Path:
    out = TRUST.with_name("trust.local.json")
    out.write_text(render_trust(anchor_arn), encoding="utf-8")
    return out


def _run(*argv: str) -> None:
    r = subprocess.run(argv, capture_output=True, text=True, check=False)  # nosec B603
    if r.returncode:
        sys.exit(f"FAILED: {argv[0]} {argv[1]} exit {r.returncode}\n{r.stdout}{r.stderr}")


def _request_serials() -> list[str]:
    """Serials of our pending requests in the user's REQUEST store (certreq leaves one behind)."""
    out = subprocess.run(["certutil", "-user", "-store", "REQUEST"],  # nosec B603 B607
                         capture_output=True, text=True, check=False).stdout
    serials, serial = [], None
    for line in out.splitlines():
        if line.startswith("Serial Number:"):
            serial = line.split(":", 1)[1].strip()
        elif line.startswith("Subject:") and f"CN={SUBJECT_CN}" in line and serial:
            serials.append(serial)
    return serials


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("cmd", choices=["issue", "show", "trust"])
    ap.add_argument("anchor_arn", nargs="?", help="trust: the trust anchor ARN from the console")
    args = ap.parse_args()
    if args.cmd == "trust":
        print(f"wrote {write_trust(args.anchor_arn or '')} (gitignored; paste it into the console)")
        return
    if sys.platform != "win32":
        sys.exit("Windows only: the key lives in the Windows TPM key store.")
    if args.cmd == "show":
        subprocess.run(["certutil", "-user", "-store", "My", SUBJECT_CN], check=False)  # nosec B603 B607
        return
    OUT.mkdir(parents=True, exist_ok=True)
    inf, csr, ca_pem, leaf_pem = (OUT / n for n in ("request.inf", "request.csr", "ca.pem", "laptop.pem"))
    inf.write_text(INF, encoding="ascii")
    csr.unlink(missing_ok=True)
    _run("certreq", "-new", "-q", "-user", str(inf), str(csr))
    ca, leaf = issue(csr.read_bytes(), dt.datetime.now(dt.UTC))
    ca_pem.write_bytes(ca)
    leaf_pem.write_bytes(leaf)
    cert = x509.load_pem_x509_certificate(leaf)
    serial = f"{cert.serial_number:x}"
    # Not `certreq -accept`: it insists on a chain to a trusted root, and adding this CA to the
    # user's Root store would make Windows trust it for everything. Instead: add the certificate,
    # link it to the TPM key (repairstore runs a signature test), drop the pending request.
    _run("certutil", "-user", "-addstore", "My", str(leaf_pem))
    _run("certutil", "-user", "-repairstore", "My", serial)
    for pending in _request_serials():
        _run("certutil", "-user", "-delstore", "REQUEST", pending)
    print(f"installed: CN={SUBJECT_CN} serial={serial} "
          f"valid until {cert.not_valid_after_utc:%Y-%m-%d %H:%M} UTC")
    print(f"trust anchor certificate (paste into the console): {ca_pem}")


if __name__ == "__main__":
    main()
